baseURL = "https://gooblog.com"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Gooblob"
summaryLength = 10
paginate = 5
disqusShortname = "gooblog"
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true
[permalinks]
  '/' = '/:section/:filename/'

[taxonomies]
  category = "category"
  tag = "tags"

[params]
  site_name = "Gooblog"
  description = "Gooblong description"
  locale = "en-US"
  type = "website"
  categories = [ 
    'games',
    'technology',
    'anime'
  ]
  instagram = '#'
  twitter = '#'
  facebook = '#'
  youtube = '#'
  

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10




