baseURL = "http://gooblog.rafthemes.com/"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Gooblob"
summaryLength = 10
paginate = 5
disqusShortname = "gooblog"
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true
enableEmoji = true
[permalinks]
  '/' = '/:section/:filename/'

[taxonomies]
  category = "category"
  tag = "tags"

[params]
  site_name = "Gooblog"
  description = "Gooblog is a site that contains articles about technology and entertainment"
  keywords = "blog, games, technology"
  locale = "en-US"
  type = "website"
  categories = [ 
    'android',
    'anime',
    'games',
    'technology',
    'trending'
  ]
  instagram = '#'
  twitter = '#'
  facebook = '#'
  youtube = '#'
  

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10
  

# json
[outputs]
  home = ["html", "json"]




