baseURL = "https://gooblob.com"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Gooblog"
summaryLength = 10
paginate = 5
disqusShortname = "gooblog"
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true

[taxonomies]
  category = "category"
  tag = "tags"

[params]
  site_name = "Gooblog"
  description = "Gooblong description"
  locale = "en-US"
  type = "website"

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1

[related]
  includeNewer = false
  threshold = 80
  toLower = false
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'date'
  weight = 10


# untuk mengganti struktur link
# [permalinks]
#   posts = ":slug"


