baseURL = "https://gooblog.netlify.app"
languageCode = "id-ID"
defaultContentLanguage = "id"
title = "Gooblog"
summaryLength = 10
paginate = 8
disqusShortname = "gooblog"
enableGitInfo = true
pygmentsCodefences = true 
pygmentsUseClasses = true

[taxonomies]
  category = "category"

[params]
  site_name = "Gooblog"
  description = "Gooblong description"
  locale = "en-US"
  type = "website"

[markup.tableOfContents]
    endLevel = 6
    startLevel = 1
  

# untuk mengganti struktur link
# [permalinks]
#   posts = ":slug"


